services:
  hass-super:
    container_name: hass-super
    image: ghcr.nju.edu.cn/hasscc/hass-super
    restart: unless-stopped
    volumes:
      - .:/var/lib/homeassistant
      - /run/dbus:/run/dbus:ro
      - docker_lib:/var/lib/docker
    environment:
      - DEFAULT_TZ=Asia/Shanghai
    devices:
      - /dev/net/tun
    hostname: hassio
    privileged: true
    network_mode: host
    healthcheck:
      test: [CMD-SHELL, curl -I localhost:8123 || exit 1]

volumes:
  docker_lib:
