services:
  hass-super:
    container_name: hass-super
    image: ghcr.nju.edu.cn/hasscc/hass-super
    restart: unless-stopped
    volumes:
      - ./hassio:/usr/share/hassio
      - /run/dbus:/run/dbus:ro
      - docker_lib:/var/lib/docker
    environment:
      - DEFAULT_TZ=Asia/Shanghai
    privileged: true
    network_mode: host

volumes:
  docker_lib:
